development:
  adapter: postgresql
  database: melvin_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: melvin_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: melvin_production
  pool: 5
  timeout: 5000
