development:
  adapter: postgresql
  database: edge_guard_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: edge_guard_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: edge_guard_production
  pool: 5
  timeout: 5000
