development:
  adapter: postgresql
  database: robertscott_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: robertscott_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: robertscott_production
  pool: 5
  timeout: 5000
